[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "out-dir-include", "tucant-language-server-derive-internal", "tucant-language-server-derive-output", "debug-adapter-protocol-macro-impl", "debug-adapter-protocol", "json-rpc-server"]

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }
diesel_derives = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }
diesel_migrations = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }

# https://github.com/rust-lang/cargo/issues/5478
[patch.'https://github.com/diesel-rs/diesel.git']
diesel = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }
diesel_derives = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }
diesel_migrations = { git = "https://github.com/diesel-rs//diesel.git", rev = "abe221d7af8455d0dba3a90a2a8aad27e8833b9d" }

[profile.dev]
split-debuginfo = "unpacked"
