[package]
name = "tucan-scraper"
version = "0.1.0"
edition = "2021"
authors = [ "Moritz Hedtke <Moritz.Hedtke@t-online.de>" ]
description = "Test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1", features = ["full"] }
html5ever = "0.26"
scraper = "0.13"
async-recursion = "1"
futures = "0.3"
diesel = { version = "2.0.0", features = ["postgres", "chrono"] }
diesel-async = { git = "https://github.com/weiznich/diesel_async", features = ["postgres", "deadpool"] }
dotenvy = "0.15"
clap = { version = "3", features = ["derive"] }
anyhow = { version = "1", features = ["backtrace"] }
regex = "1"
actix-web = "4"
futures-util = "0.3"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
actix-session = { version = "0.7", features = ["cookie-session"] }
actix-identity = "0.5"
serde_json = "1"
async-stream = { git = "https://github.com/SabrinaJewson/async-stream.rs", branch = "no-proc-macro" }
chrono = "0.4"
deadpool = "0.9"