[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "tucant-language-server-derive", "tucant-language-server-derive-internal", "tucant-language-server-derive-output"]

[profile.dev]
split-debuginfo = "unpacked"