[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "out-dir-include", "tucant-language-server-derive-internal", "tucant-language-server-derive-output", "debug-adapter-protocol-macro-impl", "debug-adapter-protocol", "json-rpc-server"]
resolver = "2"

# TODO FIXME do we need to add this to every subcrate?
[profile.dev]
split-debuginfo = "unpacked"
