[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "tucant-language-server-derive", "tucant-language-server-derive-internal", "tucant-language-server-derive-output"]
license = "AGPL-3.0-or-later"

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel.git" }

[profile.dev]
split-debuginfo = "unpacked"