[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "out-dir-include", "tucant-language-server-derive-internal", "tucant-language-server-derive-output", "debug-adapter-protocol-macro-impl", "debug-adapter-protocol", "json-rpc-server"]
resolver = "2"

# synced with https://github.com/weiznich/diesel_async/blob/main/Cargo.toml#L53
[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs//diesel", rev = "b878fed" }

# https://github.com/rust-lang/cargo/issues/5478
#[patch.'https://github.com/diesel-rs/diesel.git']
#diesel = { git = "https://github.com/diesel-rs//diesel", rev = "b878fed" }

# TODO FIXME do we need to add this to every subcrate?
[profile.dev]
split-debuginfo = "unpacked"
