[package]
name = "tucan-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1", features = ["full"] }
html5ever = "0.26"
scraper = "0.13"
async-recursion = "1"
rpassword = "7"
futures = "0.3"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite", "macros", "migrate" ] }
dotenvy = "0.15"