[workspace]
members = ["core", "tucant-language-server/fuzz_common", "tucant-language-server/fuzz_afl", "tucant-language-server/fuzz_libfuzzer", "backend", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "out-dir-include", "tucant-language-server-derive-internal", "tucant-language-server-derive-output", "debug-adapter-protocol-macro-impl", "debug-adapter-protocol", "json-rpc-server"]
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
debug = 1
