[build]
target = "./index.html"

[serve]
port = 1420
open = false

[[proxy]]
backend = "http://localhost:3000/api"

[[hooks]]
stage = "post_build"  # When to run hook, must be one of "pre_build", "build", "post_build"
command = "./fixup.sh"        # Command to run
command_arguments = [] # Arguments to pass to command