trunk-version = "^0.21.6"

[build]
target = "./index.html"

[serve]
port = 1420
open = false

# ENABLE THIS AND DISABLE THE VERSION CHECK ABOVE IF YOU USE AN UNPATCHED Trunk
# no_autoreload = true

[[proxy]]
backend = "http://localhost:3000/api"

[[hooks]]
stage = "post_build"  # When to run hook, must be one of "pre_build", "build", "post_build"
command = "bash"        # Command to run
command_arguments = ["./fixup.sh"] # Arguments to pass to command