[build]
target = "./index.html"

[serve]
port = 1420
open = false
no_autoreload = true # DO NOT CHANGE. This creates buggy navigation on Firefox

[[proxy]]
backend = "http://localhost:3000/api"

[[hooks]]
stage = "post_build"  # When to run hook, must be one of "pre_build", "build", "post_build"
command = "bash"        # Command to run
command_arguments = ["./fixup.sh"] # Arguments to pass to command