[package]
name = "tucant-language-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.12", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
itertools = "0.10.5"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
tucant_language_server_derive = { path = "../tucant-language-server-derive" }