[package]
name = "tucant-language-server-fuzz-common"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
arbitrary   = { default-features = false, version = "1", features = ["derive"] }
num-integer = { default-features = false, version = "0.1" }
num-bigint  = { default-features = false, version = "0.4" }
tucant-language-server = { path = ".." }
