[package]
name = "key-value-database"
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
indexed-db = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"

[lints]
workspace = true
