# SPDX-FileCopyrightText: The tucant Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["diesel::sql_types::*; #[cfg(feature = \"fts\")] use diesel_full_text_search::*"]
# git diff -U6 > src/schema.patch
#patch_file = "src/schema.patch"

[migrations_directory]
dir = "migrations"