[package]
name = "tucant-language-server-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
#cargo-fuzz = true

[dependencies]
afl = "*"
#libfuzzer-sys = "0.4"
arbitrary   = { default-features = false, version = "1", features = ["derive"] }
num-integer = { default-features = false, version = "0.1" }
num-bigint  = { default-features = false, version = "0.4" }

[dependencies.tucant-language-server]
path = ".."

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
