plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.6.0.cjs
