[package]
name = "tucant-language-server-fuzz-afl"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
afl = "*"
tucant-language-server-fuzz-common = { path = "../fuzz_common" }

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
