[package]
name = "tucant-language-server-fuzz-libfuzzer"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tucant-language-server-fuzz-common = { path = "../fuzz_common" }
arbitrary   = { default-features = false, version = "1", features = ["derive"] }

[[bin]]
name = "libfuzzer_fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
