[package]
name = "html-extractor"
edition = "2021"
license.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
itertools = "0.14"

[lints]
workspace = true
