[package]
name = "tucant_language_server_derive_output"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tucant_language_server_derive = { path = "../tucant-language-server-derive" }

[build-dependencies]
tucant_language_server_derive_internal = { path = "../tucant-language-server-derive-internal" }
prettyplease = "0.1"
syn = { version = "1", features = ["full", "extra-traits"] }
