[package]
name = "tucant_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
prettyplease = "0.1"
tucant_derive_lib = { path = "../backend-rust-derive-lib" }
base64 = { version = "0.13" }
heck = "0.4"
