name: Rust

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  attestations: write
  actions: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-24.04
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v4
    - run: nix build -L .#checks.x86_64-linux.my-app-fmt

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v4
    - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build .#extension
    - run: cp result tucant-extension.zip
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: tucant-extension.zip
    - uses: actions/upload-artifact@v4
      with:
        name: tucant-extension
        path: tucant-extension.zip
  
  source-code:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        DIRECTORY=$(mktemp -d)
        zip -r $DIRECTORY/tucant-extension-source.zip *
        mv $DIRECTORY/tucant-extension-source.zip tucant-extension-source.zip
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: tucant-extension-source.zip
    - uses: actions/upload-artifact@v4
      with:
        name: tucant-extension-source
        path: tucant-extension-source.zip

  reproducibility:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        attempt: [1, 2]
    steps:
    - uses: nixbuild/nix-quick-install-action@v27
    - uses: actions/checkout@v4
    - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build .#extension
    - run: cp result tucant-extension.zip
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: tucant-extension.zip
    - uses: actions/upload-artifact@v4
      with:
        name: tucant-extension-${{ matrix.attempt }}
        path: tucant-extension.zip

  reproducibility-check:
    runs-on: ubuntu-24.04
    needs: [reproducibility]
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        pattern: tucant-extension-*
    - run: ls -la -R .
    - run: nix run nixpkgs#diffoscope tucant-extension-1/tucant-extension.zip tucant-extension-2/tucant-extension.zip