name: Release extension

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: nixbuild/nix-quick-install-action@v27
    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v5
      with:
        # restore and save a cache using this key
        primary-key: nix-${{ runner.os }}
        # if there's no cache hit, restore a cache by this prefix
        restore-prefixes-first-match: nix-${{ runner.os }}-
        # collect garbage until Nix store size (in bytes) is at most this number
        # before trying to save a new cache
        gc-max-store-size-linux: 1073741824
        # do purge caches
        purge: true
        # purge all versions of the cache
        purge-prefixes: cache-${{ runner.os }}-
        # created more than this number of seconds ago relative to the start of the `Post Restore` phase
        purge-created: 0
        # except the version with the `primary-key`, if it exists
        purge-primary-key: never
    - uses: actions/checkout@v4
    - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build .#extension-unpacked .#extension-source
    - run: cp -r result/. result-chmod/
    - run: chmod -R ug+rw result-chmod/
    - run: cp result-1 result-source-code.zip
    - env:
        # https://addons.mozilla.org/en-US/developers/addon/api/key/
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#web-ext -- sign --channel unlisted --source-dir result-chmod/ --upload-source-code result-source-code.zip
    - uses: actions/upload-artifact@v4
      with:
        name: tucant-extension-xpi
        path: web-ext-artifacts/tucant-*.xpi