# SPDX-FileCopyrightText: The tucant Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --all --check
      - run: cargo install cargo-hack --locked
      - name: Build
        run: cargo hack build --workspace --all-targets
      - name: Clippy
        run: cargo hack clippy --workspace --all-targets -- -D warnings
      - name: Run tests
        run: cargo hack test --workspace --all-targets
